### ISSUE TITLE
Generate post-clustering GTF

### ISSUE THREAD

**Issue by DiogoVeiga** [DennisWangJAX/AlternativeSplicingPacBio#10]
GTF contains 1 transcript per group for each gene.

Create "reduced" transcripts at the group level.

**Comment by DiogoVeiga** [comment]
Location of the immune GTF
/projects/banchereau-lab/GTF/immune/2017March29/annotated.dontScreenMatchAnnot.gtf

**Comment by DennisWangJAX** [comment]
All the files are now under AlternativeSplicingPacBio/DailyLogProgress/3_16_Reorganized_Functions/
The main file is simplify_gff.R
It generates simplified gtf files for each gene under the default directory "simplified_gtf" and output the combined simplified gtf file in the working directory with the addition of "simplified_" in the original file name.
Already tested for the first 1000 genes(roughly 10k in total) in the smaller file.
Only the genes with more than 2 isoforms would be calculated. 
Expect more exceptions to come.

**Comment by DennisWangJAX** [comment]
File Link/Dir: https://github.com/DennisWangJAX/AlternativeSplicingPacBio/blob/master/Output_Data/200_Genes_Stats/Simplified_GTF/simplified_annotated.dontScreenMatchAnnot.gtf
