### ISSUE TITLE
Heatmap representation of isoform clusters

### ISSUE THREAD

**Issue by DiogoVeiga** [DennisWangJAX/AlternativeSplicingPacBio#6]
Use heatmaps to represent binary patterns of isoforms clusters

Columns = Exons
Rows = patterns of clusters

R package https://github.com/raivokolde/pheatmap

Colors - indicate the presence/absence of exon

Colors - indicate exon similiarity within the cluster (Jaccard index between exons, ie. intersection/union of nucleotides)

**Comment by DennisWangJAX** [comment]
The two-color heatmap is done. https://github.com/DennisWangJAX/AlternativeSplicingPacBio/blob/master/DailyLogProgress/2_28_Reorganized_Functions/heatmap_exon_binary.R

**Comment by DennisWangJAX** [comment]
Outputs in the new folder "3_1_heatmap" under Output_Data

**Comment by DennisWangJAX** [comment]
plot function: heatmap_coverage.R in the DailyLogProgress/3_1_Reorganized_Functions

**Comment by DennisWangJAX** [comment]
Outputs in the new folder "3_2_heatmap2.0" under Output_Data
